# Generated by Django 5.0.1 on 2024-01-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomCuenta', models.CharField(max_length=30, verbose_name='Nombre Cuenta')),
                ('numCuenta', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['pk'],
            },
        ),
    ]
