# Generated by Django 5.0.1 on 2024-01-16 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('direccion', models.CharField(max_length=60, verbose_name='Direccion')),
                ('numTelefono', models.CharField(max_length=10, verbose_name='Numero Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('estrato', models.IntegerField(verbose_name='Estrato')),
                ('fkDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.departamento')),
                ('fkMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.municipio')),
            ],
            options={
                'verbose_name': 'Asociados',
                'verbose_name_plural': 'Asociados',
                'ordering': ['pk'],
            },
        ),
    ]
