# Generated by Django 5.0.1 on 2024-01-18 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomBeneficiario', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('parentesco', models.CharField(choices=[('ESPOSO', 'Esposo'), ('HIJO', 'Hijo'), ('HIJA', 'Hija'), ('SOBRINO', 'Sobrino')], max_length=40, verbose_name='Parentesco')),
                ('cedula', models.FileField(blank=True, null=True, upload_to='cedula')),
                ('fkAsociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociados.asociado')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'ordering': ['pk'],
            },
        ),
    ]
